version: "2"
services:
  app:
    build:
      context: .
    command: make play
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
